apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: sit
# All resources will have -sit suffix
nameSuffix: -sit
namespace: platformcockpit
images:
  - name: sfhcm.docker.repositories.sapcdn.io/<%= config.projectName%>
    newName: sfhcm.docker.repositories.sapcdn.io/<%= config.projectName%>
    newTag: master_20200811060043-3c9cf85-4
resources:
  - ingress.yaml
bases:
  - ../../../base
