apiVersion: v1
kind: Service
metadata:
  name: <%= config.projectName%>-svc
spec:
  selector:
    app: <%= config.projectName%>
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
