apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <%= config.projectName%>-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - <%= config.projectName%>.devcluster.cksdc25.c.eu-de-1.cloud.sap
      secretName: devclustertls
  rules:
    - host: <%= config.projectName%>.devcluster.cksdc25.c.eu-de-1.cloud.sap
      http:
        paths:
          - path: /<%= config.route%>
            backend:
              serviceName: <%= config.projectName%>-svc-sit
              servicePort: 8080
