apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dc25
namespace: devportal
images:
  - name: <%= config.projectName%>
    newName: sfhcm.docker.repositories.sapcdn.io/<%= config.projectName%>
    newTag: latest
resources:
  - ingress.yaml
bases:
  - ../../../base
